name: Add New Polygon

on:
  pull_request:
    types:
      - closed
    branches:
      - main 
    paths:
      - 'newPolygon.json'

env: 
  DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
  PROD_DB_URL: ${{ secrets.PROD_DB_URL }}

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Save new polygon to db
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
    - uses: actions/checkout@v3
    - run: npm install
    - run: echo "Adding the new polygon to the db"
    - run: node addPolygonToDb.js